
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-laravel-deployment
  labels:
    app: helloworld-laravel
spec:
  selector:
    matchLabels:
      app: helloworld-laravel
  replicas: {{ .Values.frontReplicaCount }}
  template:
    metadata:
      labels:
        app: helloworld-laravel
    spec:
      containers:
      - name: helloworld-laravel
        image: marcohr89/laravelhw:latest
        ports:
        - containerPort: 8000


---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-laravel
spec:
  selector:
    app: helloworld-laravel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 
  type: {{ .Values.typeService }}