apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-dotnet-deployment
  labels:
    app: helloworld-dotnet
spec:
  selector:
    matchLabels:
      app: helloworld-dotnet
  replicas: {{ .Values.frontReplicaCount }}
  template:
    metadata:
      labels:
        app: helloworld-dotnet
    spec:
      containers:
      - name: helloworld-dotnet
        image: marcohr89/dotnet-helloworld:latest
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: helloworld-dotnet
spec:
  selector:
    app: helloworld-dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
  type: NodePort
